# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/doancea/src/bfcpp

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/doancea/src/bfcpp

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running interactive CMake command-line interface..."
	/usr/bin/cmake -i .
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/doancea/src/bfcpp/CMakeFiles /home/doancea/src/bfcpp/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/doancea/src/bfcpp/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Box

# Build rule for target.
Box: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Box
.PHONY : Box

# fast build rule for target.
Box/fast:
	$(MAKE) -f CMakeFiles/Box.dir/build.make CMakeFiles/Box.dir/build
.PHONY : Box/fast

#=============================================================================
# Target rules for targets named Oval

# Build rule for target.
Oval: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Oval
.PHONY : Oval

# fast build rule for target.
Oval/fast:
	$(MAKE) -f CMakeFiles/Oval.dir/build.make CMakeFiles/Oval.dir/build
.PHONY : Oval/fast

#=============================================================================
# Target rules for targets named bin/shapes

# Build rule for target.
bin/shapes: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 bin/shapes
.PHONY : bin/shapes

# fast build rule for target.
bin/shapes/fast:
	$(MAKE) -f CMakeFiles/bin/shapes.dir/build.make CMakeFiles/bin/shapes.dir/build
.PHONY : bin/shapes/fast

#=============================================================================
# Target rules for targets named bin/testBox

# Build rule for target.
bin/testBox: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 bin/testBox
.PHONY : bin/testBox

# fast build rule for target.
bin/testBox/fast:
	$(MAKE) -f CMakeFiles/bin/testBox.dir/build.make CMakeFiles/bin/testBox.dir/build
.PHONY : bin/testBox/fast

#=============================================================================
# Target rules for targets named bin/testOval

# Build rule for target.
bin/testOval: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 bin/testOval
.PHONY : bin/testOval

# fast build rule for target.
bin/testOval/fast:
	$(MAKE) -f CMakeFiles/bin/testOval.dir/build.make CMakeFiles/bin/testOval.dir/build
.PHONY : bin/testOval/fast

src/box.o: src/box.cpp.o
.PHONY : src/box.o

# target to build an object file
src/box.cpp.o:
	$(MAKE) -f CMakeFiles/Box.dir/build.make CMakeFiles/Box.dir/src/box.cpp.o
.PHONY : src/box.cpp.o

src/box.i: src/box.cpp.i
.PHONY : src/box.i

# target to preprocess a source file
src/box.cpp.i:
	$(MAKE) -f CMakeFiles/Box.dir/build.make CMakeFiles/Box.dir/src/box.cpp.i
.PHONY : src/box.cpp.i

src/box.s: src/box.cpp.s
.PHONY : src/box.s

# target to generate assembly for a file
src/box.cpp.s:
	$(MAKE) -f CMakeFiles/Box.dir/build.make CMakeFiles/Box.dir/src/box.cpp.s
.PHONY : src/box.cpp.s

src/oval.o: src/oval.cpp.o
.PHONY : src/oval.o

# target to build an object file
src/oval.cpp.o:
	$(MAKE) -f CMakeFiles/Oval.dir/build.make CMakeFiles/Oval.dir/src/oval.cpp.o
.PHONY : src/oval.cpp.o

src/oval.i: src/oval.cpp.i
.PHONY : src/oval.i

# target to preprocess a source file
src/oval.cpp.i:
	$(MAKE) -f CMakeFiles/Oval.dir/build.make CMakeFiles/Oval.dir/src/oval.cpp.i
.PHONY : src/oval.cpp.i

src/oval.s: src/oval.cpp.s
.PHONY : src/oval.s

# target to generate assembly for a file
src/oval.cpp.s:
	$(MAKE) -f CMakeFiles/Oval.dir/build.make CMakeFiles/Oval.dir/src/oval.cpp.s
.PHONY : src/oval.cpp.s

src/shapes.o: src/shapes.cpp.o
.PHONY : src/shapes.o

# target to build an object file
src/shapes.cpp.o:
	$(MAKE) -f CMakeFiles/bin/shapes.dir/build.make CMakeFiles/bin/shapes.dir/src/shapes.cpp.o
.PHONY : src/shapes.cpp.o

src/shapes.i: src/shapes.cpp.i
.PHONY : src/shapes.i

# target to preprocess a source file
src/shapes.cpp.i:
	$(MAKE) -f CMakeFiles/bin/shapes.dir/build.make CMakeFiles/bin/shapes.dir/src/shapes.cpp.i
.PHONY : src/shapes.cpp.i

src/shapes.s: src/shapes.cpp.s
.PHONY : src/shapes.s

# target to generate assembly for a file
src/shapes.cpp.s:
	$(MAKE) -f CMakeFiles/bin/shapes.dir/build.make CMakeFiles/bin/shapes.dir/src/shapes.cpp.s
.PHONY : src/shapes.cpp.s

tests/testbox.o: tests/testbox.cpp.o
.PHONY : tests/testbox.o

# target to build an object file
tests/testbox.cpp.o:
	$(MAKE) -f CMakeFiles/bin/testBox.dir/build.make CMakeFiles/bin/testBox.dir/tests/testbox.cpp.o
.PHONY : tests/testbox.cpp.o

tests/testbox.i: tests/testbox.cpp.i
.PHONY : tests/testbox.i

# target to preprocess a source file
tests/testbox.cpp.i:
	$(MAKE) -f CMakeFiles/bin/testBox.dir/build.make CMakeFiles/bin/testBox.dir/tests/testbox.cpp.i
.PHONY : tests/testbox.cpp.i

tests/testbox.s: tests/testbox.cpp.s
.PHONY : tests/testbox.s

# target to generate assembly for a file
tests/testbox.cpp.s:
	$(MAKE) -f CMakeFiles/bin/testBox.dir/build.make CMakeFiles/bin/testBox.dir/tests/testbox.cpp.s
.PHONY : tests/testbox.cpp.s

tests/testoval.o: tests/testoval.cpp.o
.PHONY : tests/testoval.o

# target to build an object file
tests/testoval.cpp.o:
	$(MAKE) -f CMakeFiles/bin/testOval.dir/build.make CMakeFiles/bin/testOval.dir/tests/testoval.cpp.o
.PHONY : tests/testoval.cpp.o

tests/testoval.i: tests/testoval.cpp.i
.PHONY : tests/testoval.i

# target to preprocess a source file
tests/testoval.cpp.i:
	$(MAKE) -f CMakeFiles/bin/testOval.dir/build.make CMakeFiles/bin/testOval.dir/tests/testoval.cpp.i
.PHONY : tests/testoval.cpp.i

tests/testoval.s: tests/testoval.cpp.s
.PHONY : tests/testoval.s

# target to generate assembly for a file
tests/testoval.cpp.s:
	$(MAKE) -f CMakeFiles/bin/testOval.dir/build.make CMakeFiles/bin/testOval.dir/tests/testoval.cpp.s
.PHONY : tests/testoval.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... Box"
	@echo "... Oval"
	@echo "... bin/shapes"
	@echo "... bin/testBox"
	@echo "... bin/testOval"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... src/box.o"
	@echo "... src/box.i"
	@echo "... src/box.s"
	@echo "... src/oval.o"
	@echo "... src/oval.i"
	@echo "... src/oval.s"
	@echo "... src/shapes.o"
	@echo "... src/shapes.i"
	@echo "... src/shapes.s"
	@echo "... tests/testbox.o"
	@echo "... tests/testbox.i"
	@echo "... tests/testbox.s"
	@echo "... tests/testoval.o"
	@echo "... tests/testoval.i"
	@echo "... tests/testoval.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

